name: Common Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}

jobs:
  setup:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Check for S3 Bucket
      id: check_bucket
      run: |
        if aws s3api head-bucket --bucket ${{ env.TF_STATE_BUCKET }} 2>/dev/null; then
          echo "bucket_exists=true" >> $GITHUB_ENV
        else
          echo "bucket_exists=false" >> $GITHUB_ENV
        fi

    - name: Create S3 Bucket
      if: env.bucket_exists == 'false'
      run: |
        if [ "${{ env.AWS_REGION }}" = "us-east-1" ]; then
          aws s3api create-bucket --bucket ${{ env.TF_STATE_BUCKET }}
        else
          aws s3api create-bucket --bucket ${{ env.TF_STATE_BUCKET }} --create-bucket-configuration LocationConstraint=${{ env.AWS_REGION }}
        fi

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
  
    - name: Initialize Terraform for cognito_post_confirmation
      run: |
        terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=common/cognito_post_confirmation_terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}" -backend-config="dynamodb_table=${{ env.BACKEND_TF_DYNAMODB_TABLE_NAME }}" -backend-config="encrypt=true"
      working-directory: ./terraform/common/ecr

    - name: Plan Terraform for cognito_post_confirmation
      id: terraform_plan_ecr_cognito_post_confirmation
      run: terraform plan -var="aws_region=${{ env.AWS_REGION }}" -var="image_tag=${{ github.sha }}" -out=tfplan.txt
      working-directory: ./terraform/common/ecr

    - name: Apply Terraform for cognito_post_confirmation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        terraform apply -auto-approve tfplan.txt
      working-directory: ./terraform/common/ecr

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/cognito_post_confirmation:${{ github.sha }} -f ./cognito_post_confirmation/Dockerfile .
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/cognito_post_confirmation:${{ github.sha }}

    - name: Initialize Terraform for Common Infrastructure
      run: |
        terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=common/terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}" -backend-config="dynamodb_table=${{ env.BACKEND_TF_DYNAMODB_TABLE_NAME }}" -backend-config="encrypt=true"
      working-directory: ./terraform/common

    - name: Plan Terraform for Common Infrastructure
      id: terraform_plan_ecr
      run: terraform plan -var="aws_region=${{ env.AWS_REGION }}" -var="image_tag=${{ github.sha }}" -out=tfplan.txt
      working-directory: ./terraform/common

    - name: Apply Terraform for Common Infrastructure
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        terraform apply -auto-approve tfplan.txt
      working-directory: ./terraform/common
